name: Build and Publish amd64 (default) Docker image on GitHub Container Registry
on:
  release:
    types:
      - published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.DEPLOYMENT_TOKEN }} | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/mcp-cyberbro:${{ github.event.release.tag_name }} -t ghcr.io/${{ github.repository_owner }}/mcp-cyberbro:latest .

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/mcp-cyberbro:${{ github.event.release.tag_name }} && docker push ghcr.io/${{ github.repository_owner }}/mcp-cyberbro:latest